<?php
// Download files from remote ftp and create nodes for every file.
// Load module libraries
define('MIRROR_PATH', 'sites/default/files/downloads/spring/'); //path with files that will be mirrored

function file_mirror_menu() {
  $items = array();
  $items['admin/reports/fixcron'] = array(
    'title' => t('Fix cron'),
    'page callback' => 'file_mirror_fix_cron',
    'access arguments' => array('administer file mirror'),
  );
  return $items;
}
/**
* Implementation of hook_block().
*/
function file_mirror_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Mirror block list');
      return $blocks;
    case 'view':
      $blocks['subject'] = t('Download locations');
      $blocks['content'] = 'content';
      return $blocks;
  }
}
/**
* notify upq service about changes
*/

function _file_mirror_notify_upq($url){
	$request = xmlrpc_encode_request("springfiles.upload",
	array(
		"url" => $url,
	));
	$context = stream_context_create(
	array(
		'http'=>
			array(
				'method' => 'POST',
				'header' => "Content-Type: text/xml\r\n".
				"User-Agent: drupal php bot\r\n",
				'escaping' => 'non-ascii',
				'content' => $request,
			)
		)
	);
	$file = file_get_contents('http://api.springfiles.com/xmlrpc.php', false, $context);
	if(strpos($file, 'ACK') !== false) {
		return;
	}
	$response = xmlrpc_decode($file);
	if ($response && is_array($response)) {
		if (xmlrpc_is_fault($response)) {
			$msg="xmlrpc: ".$response[faultString]." (".$response[faultCode].")";
		} else {
		$msg=print_r($response, true);
		}
	} else {
		$msg="Invalid response received: '$file'";
	}
	watchdog('file_mirror', $msg);
}

/**
* implementation of hook_nodeapi
* adds filemirror data to node object with attachment files or filefields
*/
function file_mirror_nodeapi(&$node, $op, $teaser) {
  $result = array();
  switch ($op) {
    case 'view' :
      //load and attach author information
      //$user = user_load(array('uid' = $node->author));
      
      //get all file attachments
      if (isset($node->files) && count($node->files) && user_access('view uploaded files') && !$teaser) {
          foreach ($node->files as $key => $file_attachment)
            {
              //attach mirror data to the file attachment array
              $node->files[$key]->mirrors = file_mirror_get_fid_mirrors($file_attachment->fid);
              $node->files[$key]->default_mirror = file_mirror_get_fid_defaultMirror($file_attachment->fid);
            }
      }
      //get all filefield files
      if (module_exists('filefield'))
      {
        foreach (filefield_get_field_list($node->type) as $fieldname => $filefield_data)
        {
          if (count($node->$fieldname)) {
            foreach($node->$fieldname as &$filefield)
            {
              //attach mirror data to the filefield array
              $filefield['mirrors'] = file_mirror_get_fid_mirrors($filefield['fid']);
              $filefield['default_mirror'] = file_mirror_get_fid_defaultMirror($filefield['fid']);
            }
          }
        }
      }
      break;
		case 'insert':
		case 'update':{ //check if file will be uploaded to other mirrors, if so create file to notify local cron job
			if (intval($node->field_file[0]['fid'])>0){
				$pos=strpos($node->field_file[0][filepath], MIRROR_PATH);
				if ($pos!==false){
					if ($pos==0){
//						$fid=$node->field_file[0]['fid'];
						_file_mirror_notify_upq("http://springfiles.com/".$node->field_file[0][filepath]);
					}
				}
			break;
		}
	}
  }
}

function file_mirror_get_fid_mirrors($fid) {
       $records = db_fetch_object(db_query("SELECT 'springfiles.com' as title, 'NL' as country, filepath as path, md5 FROM {files} f LEFT JOIN {filehash} h ON f.fid=h.fid  WHERE f.fid = %d AND status = 1", array($fid)));
	$array = array();
	if (is_object($records)) {
		$records->path = str_replace(file_directory_path(), '', $records->path);
		$records->path = 'downloadmain/'.$fid;
		$array[] = $records;
	}
	$content=file_get_contents("https://api.springfiles.com/json.php?md5=" . $records->md5);
	$files =json_decode($content, true);

	if (count($files) > 0) {
	foreach($files[0]["mirrors"] as $url) {
		$host = parse_url($url, PHP_URL_HOST);
		if ($host == "spring1.admin-box.com") {
			$country = "DE";
		} else {
			$country = "NL";
		}
		$array[] = (object) [
			"title" => $host,
			"country" => $country,
			"path" => $url
		];
	}
	}
       shuffle($array);
       return $array;
 }
 
function file_mirror_get_fid_defaultMirror($fid){
	$arr=file_mirror_get_fid_mirrors($fid);
	return $arr[0];
}

function _file_mirror_getfiles($lastid)
{

	$dbres = db_query('select f.fid, f.filepath, h.md5, f.filesize, f.timestamp from files f left join filehash h on f.fid = h.fid where f.fid > %d and (f.filename like "%%.sdz" or f.filename like "%%.sd7") order by f.fid limit 0,1000', array($lastid));
	$res = array();
	while ($row = db_fetch_array($dbres)) {
		$res[] = $row;
	}
	return $res;
}


/**
* Implementation of hook_xmlrpc
*/
function file_mirror_xmlrpc(){
	$methods[] = array(
			'springfiles.getfiles',
			'_file_mirror_getfiles',
			array("int", 'array'), //list of files
			t('returns the highest sync id, takes username + password as argument'),
	);
	return $methods;
}

//Drupal 6 cron issues workaround
function file_mirror_fix_cron() {
	$q = db_query("DELETE FROM `variable` WHERE name = 'cron_semaphore'");
	$q = db_query("DELETE FROM `variable` WHERE name = 'cron_last'");
	$q = db_query("DELETE FROM `variable` WHERE name = 'cron_threshold_semaphore'");
	return "fixed";
}

